name: Deploy static site to gh-pages (no Pages runner)

on:
  push:
    branches: [ main ]           # main に push されたら公開
  workflow_dispatch:             # 手動実行も可

permissions:
  contents: write                # gh-pages に push するため

jobs:
  deploy:
    runs-on: ubuntu-latest       # 普通のホストランナー（安定）

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # そのまま公開するだけなのでビルド不要。公開用ディレクトリを作る
      - name: Prepare files
        run: |
          mkdir public
          rsync -a --delete --exclude ".git" --exclude ".github" ./ public/
          touch public/.nojekyll   # Jekyll無効（既に置いてあってもOK）

      # gh-pages ブランチへ発行（force_orphan で履歴を軽量化）
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          force_orphan: true
